# Generated by Django 5.1.5 on 2025-01-21 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("phone", models.CharField(max_length=30, verbose_name="전화번호")),
                ("birth", models.DateField(verbose_name="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "남성"), ("Female", "여성")],
                        max_length=30,
                        verbose_name="성별",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("parant", "부모"),
                            ("spouse", "배우자"),
                            ("child", "자녀"),
                            ("relative", "친척"),
                            ("grandparent", "조부모"),
                            ("etc", "기타"),
                        ],
                        max_length=30,
                        verbose_name="관계",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "가족 멤버",
                "verbose_name_plural": "가족 멤버들",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "phone", "birth"), name="unique_member"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sign", models.CharField(max_length=255, verbose_name="서명")),
                ("account", models.CharField(max_length=30, verbose_name="계좌 번호")),
                ("bank", models.CharField(max_length=30, verbose_name="은행 이름")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security",
                        to="members.member",
                        verbose_name="멤버 보안",
                    ),
                ),
            ],
            options={
                "verbose_name": "보안 정보",
                "verbose_name_plural": "보안 정보들",
            },
        ),
    ]
