# Generated by Django 5.1.5 on 2025-01-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="relation",
            field=models.CharField(
                choices=[
                    ("Parant", "부모"),
                    ("Spouse", "배우자"),
                    ("Child", "자녀"),
                    ("Relative", "친척"),
                    ("Grandparent", "조부모"),
                    ("ETC", "기타"),
                ],
                max_length=30,
                verbose_name="관계",
            ),
        ),
    ]
