# Generated by Django 5.1.5 on 2025-02-06 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_member_relation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="relation",
            field=models.CharField(
                choices=[
                    ("Self", "본인"),
                    ("Parant", "부모"),
                    ("Spouse", "배우자"),
                    ("Child", "자녀"),
                    ("Relative", "친척"),
                    ("Grandparent", "조부모"),
                    ("ETC", "기타"),
                ],
                max_length=30,
                verbose_name="관계",
            ),
        ),
    ]
