# Generated by Django 5.1.5 on 2025-02-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_claim_hospital_days_claim_incident_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adddocument",
            name="page_count",
            field=models.PositiveIntegerField(default=1, verbose_name="페이지 수"),
        ),
    ]
