# Generated by Django 5.1.5 on 2025-01-21 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_alter_member_relation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=120, verbose_name="보험사")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LIFE", "종신보험"),
                            ("INDEMNITY", "실손보험"),
                            ("HEALTH", "건강종합보험"),
                        ],
                        max_length=20,
                        verbose_name="보험 종류",
                    ),
                ),
                (
                    "holder",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="계약자"
                    ),
                ),
                (
                    "insured",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="피보험자"
                    ),
                ),
                (
                    "policy_name",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="보험 이름"
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="보험료"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="보험 시작일")),
                ("end_date", models.DateField(verbose_name="보험 종료일")),
                ("payment_term", models.IntegerField(verbose_name="납입 기간")),
                (
                    "is_renewable",
                    models.BooleanField(default=False, verbose_name="갱신 여부"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "유지 중"),
                            ("expired", "만료"),
                            ("cancelled", "해지"),
                            ("pending", "대기 중"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="유지 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurances",
                        to="members.member",
                        verbose_name="가입자",
                    ),
                ),
            ],
            options={
                "verbose_name": "보험 계약",
                "verbose_name_plural": "보험 계약들",
            },
        ),
    ]
