# Generated by Django 5.1.5 on 2025-02-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurances", "0001_initial"),
        ("members", "0004_member_is_ad_agreed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurances",
                to="members.member",
                verbose_name="관리자",
            ),
        ),
    ]
