# Generated by Django 5.1.5 on 2025-02-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurances", "0002_alter_insurance_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="company",
            field=models.CharField(
                choices=[
                    (
                        "생명보험",
                        [
                            ("Samsung Life", "삼성생명"),
                            ("Kyobo Life", "교보생명"),
                            ("Hanwha Life", "한화생명"),
                            ("Shinhan Life", "신한라이프"),
                            ("DB Life", "DB생명"),
                            ("KDB Life", "KDB생명"),
                            ("NH Life", "농협생명"),
                            ("DGB Life", "DGB생명"),
                            ("AIA Life", "AIA생명"),
                            ("MetLife", "메트라이프생명"),
                            ("Prudential Life", "푸르덴셜생명"),
                            ("Heungkuk Life", "흥국생명"),
                            ("Chubb Life", "처브라이프생명"),
                            ("ABL Life", "ABL생명"),
                            ("Tongyang Life", "동양생명"),
                            ("Mirae Asset Life", "미래에셋생명"),
                            ("IBK Pension", "IBK연금보험"),
                        ],
                    ),
                    (
                        "손해보험",
                        [
                            ("Samsung Fire & Marine", "삼성화재"),
                            ("Hyundai Marine & Fire", "현대해상"),
                            ("DB Insurance", "DB손해보험"),
                            ("KB Insurance", "KB손해보험"),
                            ("Meritz Fire & Marine", "메리츠화재"),
                            ("Heungkuk Fire & Marine", "흥국화재"),
                            ("MG Non-Life", "MG손해보험"),
                            ("Hanwha General Insurance", "한화손해보험"),
                            ("NH Non-Life", "농협손해보험"),
                            ("AXA Direct", "악사손해보험"),
                            ("Lotte Insurance", "롯데손해보험"),
                            ("Carrot General Insurance", "캐롯손해보험"),
                            ("AIG General Insurance", "AIG손해보험"),
                            ("Chubb General Insurance", "처브손해보험"),
                        ],
                    ),
                    (
                        "기타보험",
                        [
                            ("Korean Federation of Community Credit", "신협공제"),
                            ("National Credit Union Federation", "새마을금고공제"),
                            ("Korea Teachers' Credit Union", "교직원공제회"),
                            ("Post Insurance", "우체국보험"),
                        ],
                    ),
                ],
                max_length=50,
                verbose_name="보험사",
            ),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="보험 종료일"),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="payment_term",
            field=models.IntegerField(blank=True, null=True, verbose_name="납입 기간"),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="보험 시작일"),
        ),
    ]
